### ISSUE TITLE
03_BehaviourTables OutMessage

### ISSUE THREAD

**Issue by gernot303** [elordin/model-transformer#1]
Braucht die OutMessage nicht eine Referenz auf Return?

**Comment by ThEngel14** [comment]
Ja du hast recht. Hab ich beim übertragen übersehen. Passe ich dann gleich an.

Von Samsung Mobile gesendetgernot303 notifications@github.com hat geschrieben:Braucht die OutMessage nicht eine Referenz auf Return?

**Comment by elordin** [comment]
fixed, jetzt (932f6a59) auch Composition statt Reference
